Update main.yml
use custom config

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,49 +45,54 @@ jobs:
         cd trunk
         for m in $TNAME;
         do
-        if [ ! -f configs/templates/$m.config ] ; then
-        echo "configs/templates/$m.config not found "
-        exit 1
-        fi
-        config="configs/templates/$m.config"
-        #####################################################################################
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' $config #删除配置项MENTOHUST
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' $config #删除配置项SOFTETHERVPN
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' $config #删除配置项SOFTETHERVPN
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' $config #删除配置项SOFTETHERVPN
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' $config #删除配置项SCUTCLIENT
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' $config #删除配置项SS plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' $config #删除配置项SS server
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' $config #删除配置项DNSFORWARDER
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' $config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' $config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' $config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' $config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' $config #删除配置项阿里DDNS
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' $config
-        ######################################################################
-        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> $config #MENTOHUST
-        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> $config #SOFTETHERVPN
-        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> $config #SOFTETHERVPN
-        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> $config #SOFTETHERVPN
-        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> $config #SCUTCLIENT
-        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> $config #SS plus+
-        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> $config #SS server
-        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> $config #DNSFORWARDER
-        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> $config #adbyby plus+
-        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> $config #内网穿透FRPC
-        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> $config #内网穿透FRPS
-        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> $config #TUNSAFE
-        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=c" >> $config #阿里DDNS
-        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> $config
-        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> $config #smartdns二进制文件
-        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=c" >> $config
-        if [ "$m" = "K2P-5.0" ] || [ "$m" = "DIR-878-5.0" ]; then
-        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> $config #v2ray二进制文件
+        if [ -f $cwd/.github/workflows/$m.config ] ; then
+          echo "use $cwd/.github/workflows/$m.config"
+          config=$cwd/.github/workflows/$m.config
         else
-        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> $config #v2ray二进制文件
+          if [ ! -f configs/templates/$m.config ] ; then
+            echo "configs/templates/$m.config not found "
+            exit 1
+          fi
+          config="configs/templates/$m.config"
+          #####################################################################################
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' $config #删除配置项MENTOHUST
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' $config #删除配置项SOFTETHERVPN
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' $config #删除配置项SOFTETHERVPN
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' $config #删除配置项SOFTETHERVPN
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' $config #删除配置项SCUTCLIENT
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' $config #删除配置项SS plus+
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' $config #删除配置项SS server
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' $config #删除配置项DNSFORWARDER
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' $config #删除配置项adbyby plus+
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' $config #删除配置项adbyby plus+
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' $config #删除配置项adbyby plus+
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' $config #删除配置项adbyby plus+
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' $config #删除配置项阿里DDNS
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' $config
+          ######################################################################
+          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> $config #MENTOHUST
+          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> $config #SOFTETHERVPN
+          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> $config #SOFTETHERVPN
+          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> $config #SOFTETHERVPN
+          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> $config #SCUTCLIENT
+          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> $config #SS plus+
+          echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> $config #SS server
+          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> $config #DNSFORWARDER
+          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> $config #adbyby plus+
+          echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> $config #内网穿透FRPC
+          echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> $config #内网穿透FRPS
+          echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> $config #TUNSAFE
+          echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=c" >> $config #阿里DDNS
+          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> $config
+          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> $config #smartdns二进制文件
+          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=c" >> $config
+          if [ "$m" = "K2P-5.0" ] || [ "$m" = "DIR-878-5.0" ]; then
+            echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> $config #v2ray二进制文件
+          else
+            echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> $config #v2ray二进制文件
+          fi
+          ####################################################################################
         fi
-        ####################################################################################
         sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" $config
         sudo ./clear_tree_simple
         sudo ./build_firmware_modify $m
